### PR TITLE
[SDPSUP-1247] Added Alert types taxonomy terms update hook.

### PR DESCRIPTION
**Pull request by MdNadimHossain**
**JIRA issue:** https://digital-engagement.atlassian.net/browse/SDPSUP-1247

### Changed

1.  Added alert type taxonomy terms update hook.

### CODE REVIEW

**Comment by vincent-gao** [comment]
Hi @MdNadimHossain , I have a questions
1. `tide_alert_update_8001` ran already at some point before. so , should it be `tide_alert_update_8002`?

**Comment by MdNadimHossain** [comment]
> Hi @MdNadimHossain , I have a questions
> 
> 1. `tide_alert_update_8001` ran already at some point before. so , should it be `tide_alert_update_8002`?

@vincent-gao this is more for the new sites because the existing sites already have that hook but in the site custom module. So the idea is to make this available for the new sites. Your thoughts?

**Comment by vincent-gao** [comment]
> > Hi @MdNadimHossain , I have a questions
> > 
> > 1. `tide_alert_update_8001` ran already at some point before. so , should it be `tide_alert_update_8002`?
> 
> @vincent-gao this is more for the new sites because the existing sites already have that hook but in the site custom module. So the idea is to make this available for the new sites. Your thoughts?

ok, but the change cannot be tested if you keep `tide_alert_update_8001`. you probably can delete `tide_alert_update_8001` and add a new `tide_alert_update_8002`?

**Comment by vincent-gao** [comment]
> > Hi @MdNadimHossain , I have a questions
> > 
> > 1. `tide_alert_update_8001` ran already at some point before. so , should it be `tide_alert_update_8002`?
> 
> @vincent-gao this is more for the new sites because the existing sites already have that hook but in the site custom module. So the idea is to make this available for the new sites. Your thoughts?

you don't want it running at old sites?

**Pull request closed without merging**
